=== accesstest3/cfunambol/modules/foundation/foundation-core/src/test/resources/data/com/funambol/server/inventory/PSDeviceInventory/dataset.dtd
<!ELEMENT dataset (
    FNBL_DEVICE_CONFIG*)>

<!ELEMENT FNBL_DEVICE_CONFIG EMPTY>
<!ATTLIST FNBL_DEVICE_CONFIG
    USERNAME    CDATA #REQUIRED
    PRINCIPAL   CDATA #REQUIRED
    URI         CDATA #REQUIRED
    VALUE       CDATA #IMPLIED
    LAST_UPDATE CDATA #IMPLIED
    STATUS      CDATA #IMPLIED
    ENCRYPTED   CDATA #IMPLIED
>

=== accesstest3/cfunambol/ds/ds-server/src/test/data/com/funambol/server/store/ConfigPersistentStore/delete-item-1-db-dataset-part-1.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="1" URI="./Email/Address" VALUE="email@address.com" LAST_UPDATE="0" STATUS ="N" ENCRYPTED="false"/>
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="1" URI="./Node1" VALUE="value1" LAST_UPDATE="0" STATUS ="D" ENCRYPTED="false"/>
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="1" URI="./Node2" VALUE="value2" LAST_UPDATE="0" STATUS ="D" ENCRYPTED="false"/>
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="1" URI="./Node3" VALUE="value3" LAST_UPDATE="999999999" STATUS ="U" ENCRYPTED="false"/>
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="1" URI="./Node4" VALUE="another value" LAST_UPDATE="999999999" STATUS ="N" ENCRYPTED="false"/>
  
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="2" URI="./Node1" VALUE="value4" LAST_UPDATE="0" STATUS ="N" ENCRYPTED="false"/>
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="2" URI="./Node2" VALUE="value5" LAST_UPDATE="1230" STATUS ="U" ENCRYPTED="false"/>
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="2" URI="./Node3" VALUE="value6" LAST_UPDATE="0" STATUS ="N" ENCRYPTED="false"/>
  
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="3" URI="./Email/Node7" VALUE="value7" LAST_UPDATE="0" STATUS ="N" ENCRYPTED="false"/>
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="3" URI="./Email/Node8" VALUE="value8" LAST_UPDATE="0" STATUS ="N" ENCRYPTED="false"/>
  
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="4" URI="./Email/Node9" VALUE="value9"  LAST_UPDATE="0" STATUS ="N" ENCRYPTED="false"/>
  
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="5" URI="./Email/Node10" VALUE="value10" LAST_UPDATE="0" STATUS ="N" ENCRYPTED="false"/>
  
  <FNBL_DEVICE_CONFIG USERNAME="user_part1" PRINCIPAL="6" URI="./Email/Node11" VALUE="value11" LAST_UPDATE="0" STATUS ="N" ENCRYPTED="false"/>
</dataset>
