=== accesstest3/cfunambol/modules/foundation/foundation-core/src/test/resources/data/com/funambol/foundation/items/dao/FileDataObjectDAO/dataset.dtd
<!ELEMENT dataset (
    FNBL_FILE_DATA_OBJECT*,
    FNBL_FILE_DATA_OBJECT_PROPERTY*)>

<!ELEMENT FNBL_FILE_DATA_OBJECT EMPTY>
<!ATTLIST FNBL_FILE_DATA_OBJECT
    id CDATA #REQUIRED
    userid CDATA #IMPLIED
    source_uri CDATA #IMPLIED
    last_update CDATA #IMPLIED
    status CDATA #IMPLIED
    upload_status CDATA #IMPLIED
    local_name CDATA #IMPLIED
    crc CDATA #IMPLIED
    true_name CDATA #IMPLIED
    created CDATA #IMPLIED
    modified CDATA #IMPLIED
    accessed CDATA #IMPLIED
    h CDATA #IMPLIED
    s CDATA #IMPLIED
    a CDATA #IMPLIED
    d CDATA #IMPLIED
    w CDATA #IMPLIED
    r CDATA #IMPLIED
    x CDATA #IMPLIED
    cttype CDATA #IMPLIED
    object_size CDATA #IMPLIED
    size_on_storage CDATA #IMPLIED
>

<!ELEMENT FNBL_FILE_DATA_OBJECT_PROPERTY EMPTY>
<!ATTLIST FNBL_FILE_DATA_OBJECT_PROPERTY
    id     CDATA #REQUIRED
    fdo_id CDATA #IMPLIED
    name   CDATA #IMPLIED
    value  CDATA #IMPLIED
>

=== accesstest3/cfunambol/modules/foundation/foundation-core/src/test/resources/data/com/funambol/foundation/items/dao/FileDataObjectDAO/exp-expired-incomplete-delete.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
    <FNBL_FILE_DATA_OBJECT id="0" userid="username1" source_uri="fdo" status="D"  upload_status="N" true_name="expiredIncompleteFDO" object_size="333333" />
    <FNBL_FILE_DATA_OBJECT id="1" userid="username1" source_uri="fdo" status="N"  upload_status="P" local_name="notExpiredIncompleteFDO.jpg" true_name="notExpiredIncompleteFDO" object_size="444444" />
    <FNBL_FILE_DATA_OBJECT id="2" userid="username1" source_uri="fdo" status="N"  upload_status="U" local_name="oldCompleteFDO.jpg" true_name="oldCompleteFDO" object_size="4545454" />
    <FNBL_FILE_DATA_OBJECT id="3" userid="username1" source_uri="fdo" status="N"  upload_status="U" true_name="oldCompleteFDO2" object_size="4545454" />
    <FNBL_FILE_DATA_OBJECT id="4" userid="username1" source_uri="fdo" status="N"  upload_status="U" local_name="recentCompleteFDO.jpg" true_name="recentCompleteFDO" object_size="4545454" />
    <FNBL_FILE_DATA_OBJECT id="20" userid="username1" source_uri="fdo" status="D" upload_status="P" true_name="expiredIncompleteFDO2" object_size="333333" />
    <FNBL_FILE_DATA_OBJECT id="21" userid="username1" source_uri="fdo" status="D" upload_status="P" true_name="expiredIncompleteFDO3" object_size="333333" />
</dataset>

=== accesstest3/cfunambol/modules/foundation/foundation-core/src/test/resources/data/com/funambol/foundation/items/dao/FileDataObjectDAO/dataset-userdb-8.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
    <FNBL_FILE_DATA_OBJECT id="0" userid="username1" source_uri="fdo" status="N" local_name="filename" crc="4274335913"/>
    <FNBL_FILE_DATA_OBJECT id="1" userid="username1" source_uri="fdo" status="N" local_name="filename" crc="4274335913"/>
    <FNBL_FILE_DATA_OBJECT id="2" userid="username1" source_uri="fdo" status="N" local_name="filename" crc="740831691"/>
    <FNBL_FILE_DATA_OBJECT id="3" userid="username1" source_uri="fdo" status="N" local_name="filename" crc="-1"/>
    <FNBL_FILE_DATA_OBJECT id="4" userid="username1" source_uri="fdo" status="N" local_name="filename" crc="-1"/>

    <FNBL_FILE_DATA_OBJECT id="5" userid="username2" status="N" local_name="filename" crc="4274335913"/>
    <FNBL_FILE_DATA_OBJECT id="6" userid="username2" status="N" local_name="filename" crc="4274335913"/>
    <FNBL_FILE_DATA_OBJECT id="7" userid="username2" status="N" local_name="filename" crc="740831691"/>
    <FNBL_FILE_DATA_OBJECT id="8" userid="username2" status="N" local_name="filename" crc="-1"/>
    <FNBL_FILE_DATA_OBJECT id="9" userid="username2" status="N" local_name="filename" crc="-1"/>
</dataset>

=== accesstest3/cfunambol/modules/foundation/foundation-core/src/test/resources/data/com/funambol/foundation/items/dao/FileDataObjectDAO/dataset-userdb-5.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
    <FNBL_FILE_DATA_OBJECT id="0" userid="username1" source_uri="fdo" last_update="1234" status="D" local_name="filename" crc="0" h="0" s="0" a="0" d="0" w="0" r="0" x="0" />
    <FNBL_FILE_DATA_OBJECT id="1" userid="username1" source_uri="fdo" last_update="1234" status="D" />
    <FNBL_FILE_DATA_OBJECT id="2" userid="username1" source_uri="fdo" last_update="1234" status="D" local_name="filename2" true_name="truename1.jpg" created="2009-04-22 09:19:42" modified="2009-04-22 10:42:32" accessed="2009-04-22 23:24:00" h="1" s="0" a="1" d="0" w="1" r="0" x="1" cttype="image/jpeg" object_size="1234" />
    <FNBL_FILE_DATA_OBJECT id="3" userid="username1" source_uri="fdo" last_update="1234" status="D" local_name="filename3" />
    <FNBL_FILE_DATA_OBJECT id="4" userid="username1" source_uri="fdo" last_update="1234" status="D" local_name="filename3" />
    <FNBL_FILE_DATA_OBJECT id="5" userid="username1" source_uri="anothersource" last_update="1234" status="N" local_name="filename" />
    <FNBL_FILE_DATA_OBJECT id="1001" userid="username1" source_uri="fdo" last_update="1234" status="D" />
</dataset>

=== accesstest3/cfunambol/modules/foundation/foundation-core/src/test/resources/data/com/funambol/foundation/items/dao/FileDataObjectDAO/dataset-userdb-6.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
    <FNBL_FILE_DATA_OBJECT id="0"    userid="username1" source_uri="fdo" last_update="2" status="N" local_name="filename"  upload_status="U" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="1"    userid="username1" source_uri="fdo" last_update="2" status="N" local_name="filename1" upload_status="U" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="1001" userid="username1" source_uri="fdo" last_update="2" status="N"/>
    <FNBL_FILE_DATA_OBJECT id="2001" userid="username1" source_uri="fdo" last_update="2" status="N" local_name="filename1" object_size="100" size_on_storage="50" />
    <FNBL_FILE_DATA_OBJECT id="2"    userid="username1" source_uri="fdo" last_update="2" status="U" local_name="filename2" upload_status="U" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="3"    userid="username1" source_uri="fdo" last_update="2" status="U" local_name="filename3" upload_status="U" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="1003" userid="username1" source_uri="fdo" last_update="2" status="U"/>
    <FNBL_FILE_DATA_OBJECT id="2003" userid="username1" source_uri="fdo" last_update="2" status="U" local_name="filename3" object_size="100" size_on_storage="50" />
    <FNBL_FILE_DATA_OBJECT id="4"    userid="username1" source_uri="fdo" last_update="2" status="D" local_name="filename4" object_size="100" upload_status="U" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="5"    userid="username1" source_uri="fdo" last_update="2" status="D" local_name="filename5" object_size="100" upload_status="U" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="1005" userid="username1" source_uri="fdo" last_update="2" status="D"/>
    <FNBL_FILE_DATA_OBJECT id="2005" userid="username1" source_uri="fdo" last_update="2" status="D" upload_status="U" local_name="filename5" object_size="100" size_on_storage="50" />

    <FNBL_FILE_DATA_OBJECT id="6"  userid="username1" source_uri="fdo" last_update="4" status="N" local_name="filename" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="7"  userid="username1" source_uri="fdo" last_update="4" status="N"/>
    <FNBL_FILE_DATA_OBJECT id="8"  userid="username1" source_uri="fdo" last_update="4" status="U" local_name="filename2" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="9"  userid="username1" source_uri="fdo" last_update="4" status="U" local_name="filename3" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="10" userid="username1" source_uri="fdo" last_update="4" status="D" local_name="filename4" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="11" userid="username1" source_uri="fdo" last_update="4" status="D" local_name="filename5" object_size="100" size_on_storage="100" />

    <FNBL_FILE_DATA_OBJECT id="20" userid="username1" source_uri="anothersource" last_update="2" status="N" local_name="filename" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="21" userid="username1" source_uri="anothersource" last_update="2" status="N"/>
    <FNBL_FILE_DATA_OBJECT id="22" userid="username1" source_uri="anothersource" last_update="2" status="U" local_name="filename2" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="23" userid="username1" source_uri="anothersource" last_update="2" status="U" local_name="filename3" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="24" userid="username1" source_uri="anothersource" last_update="2" status="D" local_name="filename4" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="25" userid="username1" source_uri="anothersource" last_update="2" status="D" local_name="filename5" object_size="100" size_on_storage="100" />

    <FNBL_FILE_DATA_OBJECT id="26" userid="username1" source_uri="anothersource" last_update="4" status="N" local_name="filename" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="27" userid="username1" source_uri="anothersource" last_update="4" status="N"/>
    <FNBL_FILE_DATA_OBJECT id="28" userid="username1" source_uri="anothersource" last_update="4" status="U" local_name="filename2" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="29" userid="username1" source_uri="anothersource" last_update="4" status="U" local_name="filename3" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="30" userid="username1" source_uri="anothersource" last_update="4" status="D" local_name="filename4" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="31" userid="username1" source_uri="anothersource" last_update="4" status="D" local_name="filename5" object_size="100" size_on_storage="100" />

    <FNBL_FILE_DATA_OBJECT id="40" userid="username2" source_uri="fdo" last_update="2" status="N" local_name="filename" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="41" userid="username2" source_uri="fdo" last_update="2" status="N"/>
    <FNBL_FILE_DATA_OBJECT id="42" userid="username2" source_uri="fdo" last_update="2" status="U" local_name="filename2" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="43" userid="username2" source_uri="fdo" last_update="2" status="U" local_name="filename3" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="44" userid="username2" source_uri="fdo" last_update="2" status="D" local_name="filename4" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="45" userid="username2" source_uri="fdo" last_update="2" status="D" local_name="filename5" object_size="100" size_on_storage="100" />

    <FNBL_FILE_DATA_OBJECT id="46" userid="username2" source_uri="fdo" last_update="4" status="N" local_name="filename" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="47" userid="username2" source_uri="fdo" last_update="4" status="N"/>
    <FNBL_FILE_DATA_OBJECT id="48" userid="username2" source_uri="fdo" last_update="4" status="U" local_name="filename2" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="49" userid="username2" source_uri="fdo" last_update="4" status="U" local_name="filename3" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="50" userid="username2" source_uri="fdo" last_update="4" status="D" local_name="filename4" object_size="100" size_on_storage="100" />
    <FNBL_FILE_DATA_OBJECT id="51" userid="username2" source_uri="fdo" last_update="4" status="D" local_name="filename5" object_size="100" size_on_storage="100" />

</dataset>
