=== accesstest3/cfunambol/modules/email/email-core/src/test/resources/data/com/funambol/email/console/dao/ConsoleDAO/dataset.dtd
<!ELEMENT dataset (
    FNBL_EMAIL_ACCOUNT*,
    FNBL_EMAIL_ENABLE_ACCOUNT*,
    FNBL_EMAIL_INBOX*,
    FNBL_EMAIL_PUSH_REGISTRY*)>

<!ELEMENT FNBL_EMAIL_ACCOUNT EMPTY>
<!ATTLIST FNBL_EMAIL_ACCOUNT
    account_id     CDATA #REQUIRED
    username       CDATA #REQUIRED
    ms_login       CDATA #REQUIRED
    ms_password    CDATA #REQUIRED
    ms_address     CDATA #REQUIRED
    ms_mailboxname CDATA #IMPLIED
    push           CDATA #IMPLIED
    soft_delete    CDATA #IMPLIED
    max_num_email  CDATA #IMPLIED
    max_imap_email CDATA #IMPLIED
    mailserver_id  CDATA #IMPLIED
    server_public  CDATA #IMPLIED
    server_type    CDATA #IMPLIED
    description    CDATA #IMPLIED
    protocol       CDATA #IMPLIED
    out_server     CDATA #IMPLIED
    out_port       CDATA #IMPLIED
    out_auth       CDATA #IMPLIED
    in_server      CDATA #IMPLIED
    in_port        CDATA #IMPLIED
    sslin          CDATA #IMPLIED
    sslout         CDATA #IMPLIED
    inbox_name     CDATA #IMPLIED
    inbox_active   CDATA #IMPLIED
    outbox_name    CDATA #IMPLIED
    outbox_active  CDATA #IMPLIED
    sent_name      CDATA #IMPLIED
    sent_active    CDATA #IMPLIED
    drafts_name    CDATA #IMPLIED
    drafts_active  CDATA #IMPLIED
    trash_name     CDATA #IMPLIED
    trash_active   CDATA #IMPLIED
    out_login      CDATA #IMPLIED
    out_password   CDATA #IMPLIED
>

<!ELEMENT FNBL_EMAIL_PUSH_REGISTRY EMPTY>
<!ATTLIST FNBL_EMAIL_PUSH_REGISTRY
    id             CDATA #REQUIRED
    period         CDATA #IMPLIED
    active         CDATA #IMPLIED
    last_update    CDATA #IMPLIED
    status         CDATA #IMPLIED
    task_bean_file CDATA #IMPLIED
>

<!ELEMENT FNBL_EMAIL_ENABLE_ACCOUNT EMPTY>
<!ATTLIST FNBL_EMAIL_ENABLE_ACCOUNT
    account_id     CDATA #REQUIRED
    username       CDATA #IMPLIED
>

<!ELEMENT FNBL_EMAIL_INBOX EMPTY>
<!ATTLIST FNBL_EMAIL_INBOX
    guid           CDATA #REQUIRED
    username       CDATA #REQUIRED
    protocol       CDATA #REQUIRED
    last_crc       CDATA #IMPLIED
    invalid        CDATA #IMPLIED
    internal       CDATA #IMPLIED
    messageid      CDATA #IMPLIED
    headerdate     CDATA #IMPLIED
    received       CDATA #IMPLIED
    subject        CDATA #IMPLIED
    sender         CDATA #IMPLIED
    token          CDATA #IMPLIED
    status         CDATA #IMPLIED
>

=== accesstest3/cfunambol/modules/email/email-core/src/test/resources/data/com/funambol/email/console/dao/ConsoleDAO/numberofunreademails_1.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "src/test/resources/data/com/funambol/email/console/dao/ConsoleDAO/dataset.dtd">
<dataset>

<!--
    FNBL_EMAIL_INBOX
    ****************
-->
<FNBL_EMAIL_INBOX   guid     ="1001"
                    username ="username100"
                    protocol ="pop"
                    received ="20090403T124700Z"
                    last_crc ="200862478"
                    />

<FNBL_EMAIL_INBOX   guid     ="1002"
                    username ="username100"
                    protocol ="pop"
                    received ="20090403T125000Z"
                    last_crc ="93782092"
                    />

<FNBL_EMAIL_INBOX   guid     ="1003"
                    username ="username100"
                    protocol ="pop"
                    received ="20090403T125300Z"
                    last_crc ="2038348370"
                    />

<FNBL_EMAIL_INBOX   guid     ="1004"
                    username ="username100"
                    protocol ="pop"
                    received ="20090101T000000Z"
                    last_crc ="3441281626"
                    />

<FNBL_EMAIL_INBOX   guid     ="1005"
                    username ="username100"
                    protocol ="pop"
                    received ="20090101T000000Z"
                    last_crc ="93782092"
                    />

<FNBL_EMAIL_INBOX   guid     ="1006"
                    username ="username100"
                    protocol ="pop"
                    received ="20090101T000000Z"
                    last_crc ="3441281626"
                    />

<FNBL_EMAIL_INBOX   guid     ="1007"
                    username ="username100"
                    protocol ="pop"
                    received ="20090101T000000Z"
                    last_crc ="200862478"
                    />

<FNBL_EMAIL_INBOX   guid     ="1008"
                    username ="username100"
                    protocol ="pop"
                    received ="20090101T000000Z"
                    last_crc ="200862478"
                    />

<FNBL_EMAIL_INBOX   guid     ="1009"
                    username ="username100"
                    protocol ="pop"
                    received ="20090101T000000Z"
                    last_crc ="2038348370"
                    />


<FNBL_EMAIL_INBOX   guid     ="11"
                    username ="username9"
                    protocol ="pop"
                    received ="20090203T030303Z"
                    last_crc ="1111144444422"
                    />

<FNBL_EMAIL_INBOX   guid     ="1031"
                    username ="username103"
                    protocol ="imap"
                    received ="20090406T153303Z"
                    last_crc ="123456789"
                    />

<FNBL_EMAIL_INBOX   guid     ="1032"
                    username ="username103"
                    protocol ="imap"
                    received ="20090406T152303Z"
                    last_crc ="93782092"
                    />

<FNBL_EMAIL_INBOX   guid     ="1033"
                    username ="username103"
                    protocol ="imap"
                    received ="20090406T150303Z"
                    last_crc ="2038348370"
                    />

<FNBL_EMAIL_INBOX   guid     ="1034"
                    username ="username103"
                    protocol ="pop"
                    received ="20090406T050303Z"
                    last_crc ="3441281626"
                    />

<FNBL_EMAIL_INBOX   guid     ="1035"
                    username ="username103"
                    protocol ="imap"
                    received ="20090405T050303Z"
                    last_crc ="3333333333"
                    />

<FNBL_EMAIL_INBOX   guid     ="1036"
                    username ="username103"
                    protocol ="imap"
                    received ="20090402T063303Z"
                    last_crc ="12345678"
                    />

</dataset>
